In [1]:
from google.colab import files
uploaded = files.upload()

Saving insurance.xlsx to insurance.xlsx

In [2]:
import pandas as pd
pd.read_excel("insurance.xlsx")

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
df = pd.read_excel("insurance.xlsx")
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [4]:
x = df[['age','sex','bmi','children','smoker','region']]

y = df['expenses']
print("Independant")
print(x.head())
print("Dependent")
print(y.head())

Independant
   age     sex   bmi  children smoker     region
0   19  female  27.9         0    yes  southwest
1   18    male  33.8         1     no  southeast
2   28    male  33.0         3     no  southeast
3   33    male  22.7         0     no  northwest
4   32    male  28.9         0     no  northwest
Dependent
0    16884.92
1     1725.55
2     4449.46
3    21984.47
4     3866.86
Name: expenses, dtype: float64

In [5]:
from sklearn.preprocessing import OneHotEncoder
x_encoaded = pd.get_dummies(x,columns=['sex','smoker','region'],drop_first=True)
print(x_encoaded.head())

   age   bmi  children  sex_male  smoker_yes  region_northwest  \
0   19  27.9         0     False        True             False
1   18  33.8         1      True       False             False
2   28  33.0         3      True       False             False
3   33  22.7         0      True       False              True
4   32  28.9         0      True       False              True

   region_southeast  region_southwest
0             False              True
1              True             False
2              True             False
3             False             False
4             False             False

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_encoaded)
print(x_scaled[:5])

[[-1.43876426 -0.4536457  -0.90861367 -1.0105187   1.97058663 -0.56641788
  -0.61132367  1.76548098]
 [-1.50996545  0.51418574 -0.07876719  0.98959079 -0.5074631  -0.56641788
   1.63579466 -0.56641788]
 [-0.79795355  0.38295436  1.58092576  0.98959079 -0.5074631  -0.56641788
   1.63579466 -0.56641788]
 [-0.4419476  -1.30664968 -0.90861367  0.98959079 -0.5074631   1.76548098
  -0.61132367 -0.56641788]
 [-0.51314879 -0.28960647 -0.90861367  0.98959079 -0.5074631   1.76548098
  -0.61132367 -0.56641788]]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train , x_test , y_train , y_test = train_test_split(
    x_scaled,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1070, 8)
(268, 8)
(1070,)
(268,)

In [9]:
from sklearn.linear_model import LinearRegression

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(x_train, y_train)

print("Linear Regression Model Trained Successfully!")

Linear Regression Model Trained Successfully!

In [10]:
y_pred = model.predict(x_test)
print(y_test.head())
print(y_pred[:5])

764      9095.07
887      5272.18
890     29330.98
1293     9301.89
259     33750.29
Name: expenses, dtype: float64
[ 8976.76760964  7061.47078348 36861.00837958  9439.16742899
 26965.82783567]

In [12]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test , y_pred)
print(r2)

0.7835726930039905

In [13]:
import joblib

# Save the trained model
joblib.dump(model, "insurance_expense_model.pkl")

print("Model saved successfully!")

Model saved successfully!